### ISSUE TITLE
AttributeError: 'QuantumCircuit' object has no attribute 'iden'

### ISSUE THREAD

**Issue by Haksell** [HuangJunye/QPong#49]
The game launches correctly, but when I want to select a level (by pressing `A`, `B` or `X`), the game crashes with the following traceback:
```
Traceback (most recent call last):
  File "main.py", line 148, in <module>
    main()
  File "main.py", line 64, in main
    level.setup(scene, ball)
  File "/Users/Haksell/Downloads/QPong-master/utils/level.py", line 30, in setup
    self.circuit = self.circuit_grid_model.compute_circuit()
  File "/Users/Haksell/Downloads/QPong-master/model/circuit_grid_model.py", line 101, in compute_circuit
    qc.iden(qr[wire_num])
AttributeError: 'QuantumCircuit' object has no attribute 'iden'
```

I use:
```
Python                 3.7.8 (installed with pyenv)
matplotlib             3.3.2
pygame                 2.0.0.dev10
qiskit                 0.23.0
qiskit-aer             0.7.0
qiskit-aqua            0.8.0
qiskit-ibmq-provider   0.11.0
qiskit-ignis           0.5.0
qiskit-terra           0.16.0
```

**Comment by panos243** [comment]
hello, I had the same problem but it is easily fixable.
You have to go to the QPong-master file , open model file, open circuit_grid_model , go to line 101 of the code witch is <<    qc.iden(qr[wire_num]) >> and replace << iden >> with << i >>. That fixed it for me.
